name: adaptive_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  googleapis: ^11.3.0
  http: ^1.1.0
  provider: ^6.0.5
  url_launcher: ^6.1.12
  flex_color_scheme: ^7.2.0
  go_router: ^10.0.0
  split_view: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
